name: release_brew

on:
  workflow_dispatch:

env:
  PACKAGE_NAME: evernote-backup

jobs:
  publish_tap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v4
        with:
          token: ${{ secrets.BREW_BUMP_TOKEN }}
          formula: ${{ env.PACKAGE_NAME }}
          tag: ${{ steps.get-latest-tag.outputs.tag }}
